# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      DBUS_SESSION_BUS_ADDRESS: unix:path=/var/run/dbus/system_bus_socket
      DISPLAY: 1
      SHELL: /usr/bin/bash

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      - name: Install D-Bus and Xvfb
        run: sudo apt-get install -y dbus-x11 xvfb

      - name: Start D-Bus
        run: sudo service dbus start

      - name: Check D-Bus Service Status
        run: sudo service dbus status

      - name: Verify D-Bus Socket Path
        run: ls /var/run/dbus/system_bus_socket
      
      - name: Start Xvfb
        run: sudo Xvfb :1 -screen 0 1024x768x24 &

      - name: Print D-Bus Address
        run: |
          echo "D-Bus Address: $DBUS_SYSTEM_BUS_ADDRESS"

      - name: Run tests with coverage (headless mode)
        run: sudo xvfb-run -e /dev/stdout npm run test:coverage

      - name: Move coverage summary
        run: npm run move-coverage

      - name: Create Coverage Badge
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          style: classic
          source: coverage/coverage-summary.json
          output: coverage/badges.svg
          jsonPath: totals.percent_covered

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
